// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: meta_event.proto

package metaeventpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MetaEventServiceClient is the client API for MetaEventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetaEventServiceClient interface {
	Noop(ctx context.Context, in *NoopAction, opts ...grpc.CallOption) (*NoopResponse, error)
	OpenShards(ctx context.Context, in *OpenShardsAction, opts ...grpc.CallOption) (*OpenShardsResponse, error)
	CloseShards(ctx context.Context, in *CloseShardsAction, opts ...grpc.CallOption) (*CloseShardsResponse, error)
	SplitShard(ctx context.Context, in *SplitShardAction, opts ...grpc.CallOption) (*SplitShardResponse, error)
	MergeShards(ctx context.Context, in *MergeShardsAction, opts ...grpc.CallOption) (*MergeShardsResponse, error)
	ChangeShardRole(ctx context.Context, in *ChangeShardRoleAction, opts ...grpc.CallOption) (*ChangeShardRoleResponse, error)
	CreateTable(ctx context.Context, in *CreateTableAction, opts ...grpc.CallOption) (*CreateTableResponse, error)
	DropTable(ctx context.Context, in *DropTableAction, opts ...grpc.CallOption) (*DropTableResponse, error)
}

type metaEventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetaEventServiceClient(cc grpc.ClientConnInterface) MetaEventServiceClient {
	return &metaEventServiceClient{cc}
}

func (c *metaEventServiceClient) Noop(ctx context.Context, in *NoopAction, opts ...grpc.CallOption) (*NoopResponse, error) {
	out := new(NoopResponse)
	err := c.cc.Invoke(ctx, "/meta_event.MetaEventService/Noop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEventServiceClient) OpenShards(ctx context.Context, in *OpenShardsAction, opts ...grpc.CallOption) (*OpenShardsResponse, error) {
	out := new(OpenShardsResponse)
	err := c.cc.Invoke(ctx, "/meta_event.MetaEventService/OpenShards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEventServiceClient) CloseShards(ctx context.Context, in *CloseShardsAction, opts ...grpc.CallOption) (*CloseShardsResponse, error) {
	out := new(CloseShardsResponse)
	err := c.cc.Invoke(ctx, "/meta_event.MetaEventService/CloseShards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEventServiceClient) SplitShard(ctx context.Context, in *SplitShardAction, opts ...grpc.CallOption) (*SplitShardResponse, error) {
	out := new(SplitShardResponse)
	err := c.cc.Invoke(ctx, "/meta_event.MetaEventService/SplitShard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEventServiceClient) MergeShards(ctx context.Context, in *MergeShardsAction, opts ...grpc.CallOption) (*MergeShardsResponse, error) {
	out := new(MergeShardsResponse)
	err := c.cc.Invoke(ctx, "/meta_event.MetaEventService/MergeShards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEventServiceClient) ChangeShardRole(ctx context.Context, in *ChangeShardRoleAction, opts ...grpc.CallOption) (*ChangeShardRoleResponse, error) {
	out := new(ChangeShardRoleResponse)
	err := c.cc.Invoke(ctx, "/meta_event.MetaEventService/ChangeShardRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEventServiceClient) CreateTable(ctx context.Context, in *CreateTableAction, opts ...grpc.CallOption) (*CreateTableResponse, error) {
	out := new(CreateTableResponse)
	err := c.cc.Invoke(ctx, "/meta_event.MetaEventService/CreateTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metaEventServiceClient) DropTable(ctx context.Context, in *DropTableAction, opts ...grpc.CallOption) (*DropTableResponse, error) {
	out := new(DropTableResponse)
	err := c.cc.Invoke(ctx, "/meta_event.MetaEventService/DropTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaEventServiceServer is the server API for MetaEventService service.
// All implementations must embed UnimplementedMetaEventServiceServer
// for forward compatibility
type MetaEventServiceServer interface {
	Noop(context.Context, *NoopAction) (*NoopResponse, error)
	OpenShards(context.Context, *OpenShardsAction) (*OpenShardsResponse, error)
	CloseShards(context.Context, *CloseShardsAction) (*CloseShardsResponse, error)
	SplitShard(context.Context, *SplitShardAction) (*SplitShardResponse, error)
	MergeShards(context.Context, *MergeShardsAction) (*MergeShardsResponse, error)
	ChangeShardRole(context.Context, *ChangeShardRoleAction) (*ChangeShardRoleResponse, error)
	CreateTable(context.Context, *CreateTableAction) (*CreateTableResponse, error)
	DropTable(context.Context, *DropTableAction) (*DropTableResponse, error)
	mustEmbedUnimplementedMetaEventServiceServer()
}

// UnimplementedMetaEventServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMetaEventServiceServer struct {
}

func (UnimplementedMetaEventServiceServer) Noop(context.Context, *NoopAction) (*NoopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Noop not implemented")
}
func (UnimplementedMetaEventServiceServer) OpenShards(context.Context, *OpenShardsAction) (*OpenShardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenShards not implemented")
}
func (UnimplementedMetaEventServiceServer) CloseShards(context.Context, *CloseShardsAction) (*CloseShardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseShards not implemented")
}
func (UnimplementedMetaEventServiceServer) SplitShard(context.Context, *SplitShardAction) (*SplitShardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SplitShard not implemented")
}
func (UnimplementedMetaEventServiceServer) MergeShards(context.Context, *MergeShardsAction) (*MergeShardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MergeShards not implemented")
}
func (UnimplementedMetaEventServiceServer) ChangeShardRole(context.Context, *ChangeShardRoleAction) (*ChangeShardRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeShardRole not implemented")
}
func (UnimplementedMetaEventServiceServer) CreateTable(context.Context, *CreateTableAction) (*CreateTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTable not implemented")
}
func (UnimplementedMetaEventServiceServer) DropTable(context.Context, *DropTableAction) (*DropTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropTable not implemented")
}
func (UnimplementedMetaEventServiceServer) mustEmbedUnimplementedMetaEventServiceServer() {}

// UnsafeMetaEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetaEventServiceServer will
// result in compilation errors.
type UnsafeMetaEventServiceServer interface {
	mustEmbedUnimplementedMetaEventServiceServer()
}

func RegisterMetaEventServiceServer(s grpc.ServiceRegistrar, srv MetaEventServiceServer) {
	s.RegisterService(&MetaEventService_ServiceDesc, srv)
}

func _MetaEventService_Noop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoopAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEventServiceServer).Noop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta_event.MetaEventService/Noop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEventServiceServer).Noop(ctx, req.(*NoopAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEventService_OpenShards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenShardsAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEventServiceServer).OpenShards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta_event.MetaEventService/OpenShards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEventServiceServer).OpenShards(ctx, req.(*OpenShardsAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEventService_CloseShards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseShardsAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEventServiceServer).CloseShards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta_event.MetaEventService/CloseShards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEventServiceServer).CloseShards(ctx, req.(*CloseShardsAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEventService_SplitShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SplitShardAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEventServiceServer).SplitShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta_event.MetaEventService/SplitShard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEventServiceServer).SplitShard(ctx, req.(*SplitShardAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEventService_MergeShards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeShardsAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEventServiceServer).MergeShards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta_event.MetaEventService/MergeShards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEventServiceServer).MergeShards(ctx, req.(*MergeShardsAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEventService_ChangeShardRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeShardRoleAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEventServiceServer).ChangeShardRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta_event.MetaEventService/ChangeShardRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEventServiceServer).ChangeShardRole(ctx, req.(*ChangeShardRoleAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEventService_CreateTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTableAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEventServiceServer).CreateTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta_event.MetaEventService/CreateTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEventServiceServer).CreateTable(ctx, req.(*CreateTableAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetaEventService_DropTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropTableAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaEventServiceServer).DropTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/meta_event.MetaEventService/DropTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaEventServiceServer).DropTable(ctx, req.(*DropTableAction))
	}
	return interceptor(ctx, in, info, handler)
}

// MetaEventService_ServiceDesc is the grpc.ServiceDesc for MetaEventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetaEventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meta_event.MetaEventService",
	HandlerType: (*MetaEventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Noop",
			Handler:    _MetaEventService_Noop_Handler,
		},
		{
			MethodName: "OpenShards",
			Handler:    _MetaEventService_OpenShards_Handler,
		},
		{
			MethodName: "CloseShards",
			Handler:    _MetaEventService_CloseShards_Handler,
		},
		{
			MethodName: "SplitShard",
			Handler:    _MetaEventService_SplitShard_Handler,
		},
		{
			MethodName: "MergeShards",
			Handler:    _MetaEventService_MergeShards_Handler,
		},
		{
			MethodName: "ChangeShardRole",
			Handler:    _MetaEventService_ChangeShardRole_Handler,
		},
		{
			MethodName: "CreateTable",
			Handler:    _MetaEventService_CreateTable_Handler,
		},
		{
			MethodName: "DropTable",
			Handler:    _MetaEventService_DropTable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "meta_event.proto",
}
